"""Stable string vocabulary for the future universal runtime."""

from enum import Enum

try:
    from enum import StrEnum
except ImportError:  # pragma: no cover - compatibility with Python < 3.11
    class StrEnum(str, Enum):
        """Minimal standard-library-compatible StrEnum fallback."""


class EvidenceStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"


class BindingStatus(StrEnum):
    BOUND = "BOUND"
    INTERFACE_ONLY = "INTERFACE_ONLY"
    UNRESOLVED = "UNRESOLVED"


class TurnKind(StrEnum):
    NORMAL = "NORMAL"
    EXTRA = "EXTRA"
    INTERRUPT = "INTERRUPT"
    NONE = "NONE"


class ActionFamily(StrEnum):
    NORMAL_TURN = "NORMAL_TURN"
    EXTRA_TURN = "EXTRA_TURN"
    EXTRA_ACTION = "EXTRA_ACTION"
    FOLLOW_UP = "FOLLOW_UP"
    COUNTER = "COUNTER"
    ULTIMATE_INTERRUPT = "ULTIMATE_INTERRUPT"
    DOES_NOT_END_TURN = "DOES_NOT_END_TURN"
    SUMMON_ACTION = "SUMMON_ACTION"
    JOINT_ACTION = "JOINT_ACTION"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class PriorityClass(StrEnum):
    FOLLOW_UP = "FOLLOW_UP"
    ULTIMATE_OR_EXTRA_TURN = "ULTIMATE_OR_EXTRA_TURN"
    DOES_NOT_END_TURN = "DOES_NOT_END_TURN"
    NORMAL_TURN = "NORMAL_TURN"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class SamePriorityPolicy(StrEnum):
    FIFO = "FIFO"
    LIFO = "LIFO"
    EXPLICIT_ORDER = "EXPLICIT_ORDER"
    UNRESOLVED = "UNRESOLVED"


class TargetPolicyKind(StrEnum):
    SINGLE = "SINGLE"
    BLAST = "BLAST"
    AOE = "AOE"
    BOUNCE = "BOUNCE"
    RANDOM = "RANDOM"
    LOCKED = "LOCKED"
    ADJACENT = "ADJACENT"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class TargetInvalidationPolicy(StrEnum):
    ABORT = "ABORT"
    RETARGET_RANDOM = "RETARGET_RANDOM"
    RETARGET_LOCKED = "RETARGET_LOCKED"
    RETARGET_MARKED = "RETARGET_MARKED"
    WAIT_FOR_NEW_TARGET = "WAIT_FOR_NEW_TARGET"
    CONTINUE_CHAIN = "CONTINUE_CHAIN"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class MultiHitContinuationPolicy(StrEnum):
    STOP = "STOP"
    RETARGET = "RETARGET"
    CONTINUE_ON_CORPSE = "CONTINUE_ON_CORPSE"
    CONTINUE_CHAIN = "CONTINUE_CHAIN"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class BounceRepeatPolicy(StrEnum):
    WITH_REPLACEMENT = "WITH_REPLACEMENT"
    WITHOUT_REPLACEMENT = "WITHOUT_REPLACEMENT"
    WEIGHTED = "WEIGHTED"
    CONTENT_DEFINED = "CONTENT_DEFINED"
    UNRESOLVED = "UNRESOLVED"


class TriggerScope(StrEnum):
    PER_ACTION = "PER_ACTION"
    PER_ATTACK = "PER_ATTACK"
    PER_HIT = "PER_HIT"
    PER_TARGET = "PER_TARGET"
    PER_DISTINCT_TARGET = "PER_DISTINCT_TARGET"
    PER_EFFECT_ACTIVATION = "PER_EFFECT_ACTIVATION"
    PER_TURN = "PER_TURN"
    PER_WAVE = "PER_WAVE"
    PER_BATTLE = "PER_BATTLE"


class StackPolicy(StrEnum):
    NON_STACKING = "NON_STACKING"
    ADD_STACK = "ADD_STACK"
    EXTEND_DURATION = "EXTEND_DURATION"
    REFRESH_DURATION = "REFRESH_DURATION"
    REPLACE_VALUE = "REPLACE_VALUE"
    INDEPENDENT_INSTANCES = "INDEPENDENT_INSTANCES"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class WavePolicy(StrEnum):
    KEEP = "KEEP"
    REMOVE = "REMOVE"
    RESET_COUNTER = "RESET_COUNTER"
    KEEP_AV = "KEEP_AV"
    REBASE_AV = "REBASE_AV"
    REAPPLY = "REAPPLY"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class RemovalChannel(StrEnum):
    CLEANSE = "CLEANSE"
    DISPEL = "DISPEL"
    NATURAL_EXPIRATION = "NATURAL_EXPIRATION"
    TRANSFORM = "TRANSFORM"
    WEAKNESS_BREAK = "WEAKNESS_BREAK"
    KILLING_BLOW = "KILLING_BLOW"
    OWNER_DOWNED = "OWNER_DOWNED"
    COUNTDOWN = "COUNTDOWN"
    RESOURCE_DEPLETION = "RESOURCE_DEPLETION"
    LINKED_ENTITY_DEFEATED = "LINKED_ENTITY_DEFEATED"
    PHASE_CHANGE = "PHASE_CHANGE"
    SCRIPTED = "SCRIPTED"


class LifecycleState(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    CROWD_CONTROLLED = "CROWD_CONTROLLED"
    OFF_FIELD = "OFF_FIELD"
    UNTARGETABLE = "UNTARGETABLE"
    REMOVED = "REMOVED"
    KNOCKED_DOWN = "KNOCKED_DOWN"
    DEAD = "DEAD"
    PENDING_REVIVE = "PENDING_REVIVE"
    REVIVING = "REVIVING"
    REVIVED = "REVIVED"
    DESPAWNED = "DESPAWNED"


class QuantizationPolicy(StrEnum):
    NONE = "NONE"
    FLOOR = "FLOOR"
    CEIL = "CEIL"
    ROUND_HALF_UP = "ROUND_HALF_UP"
    ROUND_HALF_EVEN = "ROUND_HALF_EVEN"
    TRUNCATE = "TRUNCATE"
    DISPLAY_ONLY = "DISPLAY_ONLY"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class DotEvaluationPolicy(StrEnum):
    SNAPSHOT = "SNAPSHOT"
    DYNAMIC = "DYNAMIC"
    HYBRID = "HYBRID"
    CONTENT_DEFINED = "CONTENT_DEFINED"
    UNRESOLVED = "UNRESOLVED"


class MaxHpCouplingPolicy(StrEnum):
    PRESERVE_CURRENT = "PRESERVE_CURRENT"
    PRESERVE_RATIO = "PRESERVE_RATIO"
    ADD_DELTA = "ADD_DELTA"
    CLAMP_ONLY = "CLAMP_ONLY"
    LINK_PERCENTAGE = "LINK_PERCENTAGE"
    CONTENT_DEFINED = "CONTENT_DEFINED"
    UNRESOLVED = "UNRESOLVED"


class DamageFamily(StrEnum):
    DIRECT = "DIRECT"
    DOT = "DOT"
    BREAK = "BREAK"
    SUPER_BREAK = "SUPER_BREAK"
    ADDITIONAL = "ADDITIONAL"
    TRUE = "TRUE"
    ELATION = "ELATION"
    ENCOUNTER_SCRIPTED = "ENCOUNTER_SCRIPTED"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class DefenseMechanism(StrEnum):
    NORMAL_SHIELD_INSTANCE = "NORMAL_SHIELD_INSTANCE"
    STACKABLE_SHIELD_FAMILY = "STACKABLE_SHIELD_FAMILY"
    COLLECTIVE_SHIELD_POOL = "COLLECTIVE_SHIELD_POOL"
    BARRIER = "BARRIER"
    DMG_MITIGATION = "DMG_MITIGATION"
    DAMAGE_DISTRIBUTION = "DAMAGE_DISTRIBUTION"
    HP_FLOOR = "HP_FLOOR"
    LETHAL_INTERCEPT = "LETHAL_INTERCEPT"
    SCRIPTED_INVULNERABILITY = "SCRIPTED_INVULNERABILITY"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class TargetRole(StrEnum):
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"
    ADJACENT = "ADJACENT"
    BOUNCE = "BOUNCE"
    AOE = "AOE"
    RANDOM = "RANDOM"
    LOCKED = "LOCKED"
    CONTENT_DEFINED = "CONTENT_DEFINED"


class RuntimeResourceKind(StrEnum):
    ENERGY = "ENERGY"
    SKILL_POINTS = "SKILL_POINTS"


class RuntimeResourceScope(StrEnum):
    UNIT = "UNIT"
    TEAM = "TEAM"


class RuntimeEventType(StrEnum):
    BATTLE_START = "BATTLE_START"
    WAVE_START = "WAVE_START"
    TURN_ENTRY = "TURN_ENTRY"
    TURN_START = "TURN_START"
    ACTION_QUEUED = "ACTION_QUEUED"
    ACTION_START = "ACTION_START"
    ACTION_VALUE_ADVANCED = "ACTION_VALUE_ADVANCED"
    ATTACK_DECLARED = "ATTACK_DECLARED"
    ATTACK_CONTACT = "ATTACK_CONTACT"
    TARGET_ATTACKED = "TARGET_ATTACKED"
    HIT_RESOLVED = "HIT_RESOLVED"
    BEFORE_DAMAGE = "BEFORE_DAMAGE"
    DAMAGE_RESOLVED = "DAMAGE_RESOLVED"
    SHIELD_CHANGED = "SHIELD_CHANGED"
    SHIELD_DAMAGED = "SHIELD_DAMAGED"
    HP_CHANGED = "HP_CHANGED"
    HP_DAMAGED = "HP_DAMAGED"
    HP_LOST = "HP_LOST"
    TOUGHNESS_REDUCED = "TOUGHNESS_REDUCED"
    WEAKNESS_BROKEN = "WEAKNESS_BROKEN"
    ENERGY_CHANGED = "ENERGY_CHANGED"
    SKILL_POINTS_CHANGED = "SKILL_POINTS_CHANGED"
    EFFECT_APPLICATION_ATTEMPT = "EFFECT_APPLICATION_ATTEMPT"
    EFFECT_APPLIED = "EFFECT_APPLIED"
    EFFECT_RESISTED = "EFFECT_RESISTED"
    EFFECT_IMMUNE = "EFFECT_IMMUNE"
    EFFECT_REMOVED = "EFFECT_REMOVED"
    EFFECT_TRANSFORMED = "EFFECT_TRANSFORMED"
    FOLLOW_UP_QUEUED = "FOLLOW_UP_QUEUED"
    COUNTER_QUEUED = "COUNTER_QUEUED"
    EXTRA_TURN_QUEUED = "EXTRA_TURN_QUEUED"
    ACTION_END = "ACTION_END"
    TURN_END = "TURN_END"
    BEFORE_LETHAL = "BEFORE_LETHAL"
    LETHAL_INTERCEPTED = "LETHAL_INTERCEPTED"
    DOWNED = "DOWNED"
    KNOCKED_DOWN = "KNOCKED_DOWN"
    DEATH = "DEATH"
    REVIVE = "REVIVE"
    WAVE_END = "WAVE_END"
    BATTLE_END = "BATTLE_END"
    CONTENT_DEFINED = "CONTENT_DEFINED"
